// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// multiKernel
SEXP multiKernel(SEXP Ys, SEXP Zs, SEXP Ks, double tau);
RcppExport SEXP multiKernel_multiKernel(SEXP YsSEXP, SEXP ZsSEXP, SEXP KsSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type Ys(YsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Zs(ZsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Ks(KsSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    __result = Rcpp::wrap(multiKernel(Ys, Zs, Ks, tau));
    return __result;
END_RCPP
}
