# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

multiKernel_cpp <- function(Yr, Zr, Kr, tau) {
    .Call('multiKernel_multiKernel', PACKAGE = 'multiKernel', Yr, Zr, Kr, tau)
}

multiKernel_noCon_cpp <- function(Yr, Kr, tau) {
    .Call('multiKernel_multiKernel_noCon', PACKAGE = 'multiKernel', Yr, Kr, tau)
}

